### ISSUE TITLE
同学，问下我这个为什么报错了

### ISSUE THREAD

**Issue by MrKou47** [Emeryao/we-app-typescript#1]
```
D:\n_workspace\we-app-typescript>gulp
[18:03:32] Using gulpfile D:\n_workspace\we-app-typescript\gulpfile.js
[18:03:32] Starting 'build'...
src/app.ts(4,15): error TS1311: Async functions are only available when targeting ECMAScript 2015 or higher.
src/app.ts(11,1): error TS1311: Async functions are only available when targeting ECMAScript 2015 or higher.
src/utils/http-client.ts(4,19): error TS1311: Async functions are only available when targeting ECMAScript 2015 or higher.
src/utils/http-client.ts(31,19): error TS1311: Async functions are only available when targeting ECMAScript 2015 or higher.
[18:03:34] 'build' errored after 2.05 s
[18:03:34] Error: Command failed: tsc
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at Gulp.gulp.task (D:\n_workspace\we-app-typescript\gulpfile.js:16:5)
    at module.exports (D:\n_workspace\we-app-typescript\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\n_workspace\we-app-typescript\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\n_workspace\we-app-typescript\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\n_workspace\we-app-typescript\node_modules\orchestrator\index.js:134:8)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

D:\n_workspace\we-app-typescript>
```

**Comment by emeryao** [comment]
嗯 看一下你装的TypeScript的版本
```
tsc --version
```
现在最新的是2.1.4
我想应该是你的TypeScript版本太低了
@MrKou47

**Comment by zijing07** [comment]
一样的问题，我的 typescript 版本是 2.4.1  的，如果有啥想法希望回复讨论一下

**Comment by zijing07** [comment]
我把我机器上的npm缓存全部都删了一次，终于好了。其实我觉得可以不用gulp这么大的东西，只用tsc应该就可以了吧，另外都装成全局的也不是很好。只是一点建议，可能不对。

感谢作者！

**Comment by emeryao** [comment]
只用`tsc`的话 只是编译了ts
gulp是用来copy别的像html/css之类的文件用的

至于装不装全局纯粹是个人喜好/习惯了

不客气 @zijing07
