### ISSUE TITLE
async 出错

### ISSUE THREAD

**Issue by liny4cn** [Emeryao/we-app-typescript#2]
thirdScriptError
regeneratorRuntime is not defined;at App lifeCycleMethod onLaunch function
ReferenceError: regeneratorRuntime is not defined
    at e.onLaunch (http://127.0.0.1:9973/appservice/app.js:29:66)
    at e.r (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:15233)
    at new e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:16623)
    at Function.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:17063)
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:14:29278
    at http://127.0.0.1:9973/appservice/app.js:27:1
    at require (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:18238)
    at http://127.0.0.1:9973/appservice/appservice:1087:9

**Comment by emeryao** [comment]
try to use the codes in [`promise-inject`](https://github.com/Emeryao/we-app-typescript/tree/promise-inject) branch

**Comment by liny4cn** [comment]
Thanks. It's ok. 

So, I changed the 'tsconfig.json' file below to fix it:
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "lib": [
            "esnext",
            "dom"
        ]
